server:
  port: 8081
  servlet:
    context-path: /admin

spring:
  application:
    name: admin-service

  # MongoDB
  data:
    mongodb:
      uri: mongodb://admin:roomie123@localhost:27017/roomie_admin?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: roomie123
      timeout: 60000

  # Elasticsearch
  elasticsearch:
      uris: http://localhost:9200

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-consumers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Custom config
admin:
  super-admin-email: admin@roomie.com
  admin-jwt-secret: roomie-admin-jwt-secret-key-must-be-at-least-256-bits-long-very-important
  session-timeout-hours: 8

app:
  services:
    identity: http://localhost:8080/identity
    properties: http://localhost:8083/properties