global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'auth-service:8080'
          - 'property-service:8083'
          - 'api-gateway:8888'
    scrape_interval: 10s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']