server:
  port: 8087
  servlet:
    context-path: /payment
spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb://admin:roomie123@localhost:27017/roomie_payment?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: roomie123
      timeout: 5000ms

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

vnpay:
  merchantCode: TIZRZATK
  secretKey: ODAAEO744ZVZFPQGZHS3XTUE73508BHX
  returnUrl: http://localhost:8087/api/payments/webhook/vnpay

momo:
  partnerCode: MOMORZW420251202_TEST
  accessKey: BeMUhv9rHCRg517u
  secretKey: nl90qNFWwXrVOkf9uDWsYPUZ4bIr4gTb
  returnUrl: http://localhost:8087/api/payments/webhook/momo
  notifyUrl: http://localhost:8087/api/payments/webhook/momo
