server:
  port: 8088
  servlet:
    context-path: /file

spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://admin:roomie123@localhost:27017/roomie_profile?authSource=admin
      database: roomie_profile
    redis:
      host: localhost
      port: 6379
      password: roomie123
      timeout: 5000ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  file:
    storage-dir: C:/upload
    download-prefix: http://localhost:8888/api/v1/file/media/download/

  minio:
    endpoint: http://localhost:9000
    bucket: roomie-files
    access-key: roomie
    secret-key: roomie123
