server:
  port: 8085
  servlet:
    context-path: /chat

spring:
  application:
    name: chat-service

  data:
    mongodb:
      uri: mongodb://admin:roomie123@localhost:27017/roomie_chat?authSource=admin
      auto-index-creation: true

app:
  services:
    profile: http://localhost:8081/profile
    identity: http://localhost:8080/identity