server:
  port: 8089
  servlet:
    context-path: /chat

spring:
  application:
    name: chat-service

  data:
    mongodb:
      uri: mongodb://admin:roomie123@localhost:27017/roomie_chat?authSource=admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      password: roomie123

app:
  services:
    profile: http://localhost:8082/profile
    identity: http://localhost:8080/identity