server:
  port: 8084
  servlet:
    context-path: /bookings

spring:
  application:
    name: booking-service

  data:
    mongodb:
      uri: mongodb://admin:roomie123@localhost:27017/roomie_booking?authSource=admin
    redis:
      host: redis
      port: 6379
      password: #roomie123
      timeout: 5000ms

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka
      register-with-eureka: true
      fetch-registry: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: booking-service
      properties:
        spring.json.trusted.packages: "*"

  booking:
    redis:
      lock-ttl: 900000 # 15 minutes
      pending-ttl: 900000

  cache:
    type: redis

app:
  services:
    properties: http://localhost:8083/properties

