server:
  port: 8094
  servlet:
    context-path: /bills

spring:
  application:
    name: billing-service

  data:
    mongodb:
      uri: mongodb://admin:roomie123@localhost:27017/roomie_billing?authSource=admin

    redis:
      host: localhost
      port: 6379
      password: roomie123

  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: billing-service

billing:
  cycle-day: 1
  due-days: 30
  late-fee-percentage: 5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  services:
    contract: http://localhost:8091/contracts